plugins {
    id 'com.android.application'
}

android {
    namespace 'com.fhp.macro'
    compileSdk 34

    defaultConfig {
        applicationId 'com.fhp.macro'
        minSdk 24
        targetSdk 34
        versionCode 2
        versionName '2.0'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}

dependencies {
    implementation 'androidx.core:core-ktx:1.13.1'
}